name: Build and ZIP Unity CS Lambda Authorizer Workflow
on: [push, workflow_dispatch]
jobs:
  build_source:
    name: build and zip lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
      - name: Create ZIP file
        run: zip -r ./unity-cs-lambda-auth.zip node_modules package.json index.js
        working-directory: ./
#       - name: Commit and push
#         uses: EndBug/add-and-commit@v7
#         with:
#           add: '["./unity-cs-lambda-auth.zip"]'
#           message: 'Add unity-cs-lambda-auth.zip'
#           push: true
      - name: Get release
        id: '107445246'
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./unity-cs-lambda-auth.zip
          asset_name: unity-cs-lambda-auth-${{ steps.latest_release_info.outputs.tag_name }}.zip
          asset_content_type: application/zip
